# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 16:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorie',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='Article',
            new_name='Post',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='nom',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='auteur',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='categorie',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='contenu',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='titre',
            new_name='title',
        ),
    ]
